apiVersion: v1
kind: Service
metadata:
  name: nl-api-flask
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: nl-api-flask
