apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api-preprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/NickLavrov/nl-api-argocd-config.git"
    path: environments/preprod/my-api
    helm:
      valueFiles:
        - values.yaml
      repositories:
        - name: eks
          url: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{`{{namespace}}`}}"
  syncPolicy:
    automated: {}
